return {
	"tjdevries/colorbuddy.nvim",

	"ribru17/bamboo.nvim",
	"zootedb0t/citruszest.nvim",
	"scottmckendry/cyberdream.nvim",
	"sekke276/dark_flat.nvim",
	"Verf/deepwhite.nvim",
	"Mofiqul/dracula.nvim",
	"eldritch-theme/eldritch.nvim",
	"savq/melange-nvim",
	"miikanissi/modus-themes.nvim",
	"shaunsingh/moonlight.nvim",
	"svrana/neosolarized.nvim",
	"EdenEast/nightfox.nvim",
	"Yazeed1s/oh-lucy.nvim",
	"navarasu/onedark.nvim",
	"rmehri01/onenord.nvim",
	"nyoom-engineering/oxocarbon.nvim",
	"olivercederborg/poimandres.nvim",
	"shaunsingh/seoul256.nvim",
	"NTBBloodbath/sweetie.nvim",
	"folke/tokyonight.nvim",
	"Mofiqul/vscode.nvim",
	-- Add in any other configuration;
	--   event = foo,
	--   config = bar
	--   end,
	lazy = false,
	priority = 1000,
}
