return {
	{ "tjdevries/colorbuddy.nvim", lazy = true },
	{ "ribru17/bamboo.nvim", lazy = true },
	{ "zootedb0t/citruszest.nvim", lazy = true },
	{ "scottmckendry/cyberdream.nvim", lazy = true },
	{ "sekke276/dark_flat.nvim", lazy = true },
	{ "Verf/deepwhite.nvim", lazy = true },
	{ "Mofiqul/dracula.nvim", lazy = true },
	{ "eldritch-theme/eldritch.nvim", lazy = true },
	{ "maxmx03/fluoromachine.nvim", lazy = true },
	{ "sainnhe/sonokai", lazy = true },
	{ "craftzdog/solarized-osaka.nvim", lazy = true },
	{ "sainnhe/everforest", lazy = true },
	{ "rebelot/kanagawa.nvim", lazy = true },
	{ "catppuccin/nvim", lazy = true },
	{ "smit4k/shale.nvim", lazy = true },
	{ "savq/melange-nvim", lazy = true },
	{ "miikanissi/modus-themes.nvim", lazy = true },
	{ "shaunsingh/moonlight.nvim", lazy = true },
	{ "svrana/neosolarized.nvim", lazy = true },
	{ "EdenEast/nightfox.nvim", lazy = true },
	{ "Yazeed1s/oh-lucy.nvim", lazy = true },
	{ "navarasu/onedark.nvim", lazy = true },
	{ "rmehri01/onenord.nvim", lazy = true },
	{ "nyoom-engineering/oxocarbon.nvim", lazy = true },
	{ "olivercederborg/poimandres.nvim", lazy = true },
	{ "junegunn/seoul256.vim", lazy = true },
	{ "NTBBloodbath/sweetie.nvim", lazy = true },
	{ "folke/tokyonight.nvim", lazy = true, priority = 1000 },
	{ "Mofiqul/vscode.nvim", lazy = true },
}
